stages:
  - determine
  - build

variables:
  SOLUTION_FILE: "Pulsar.sln"
  BUILD_CONFIGURATION: "Release"
  TARGET_FRAMEWORK: "net472"

# Only run on main branch when C# files or project files change
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - "**/*.cs"
        - "**/*.csproj"
        - "**/*.sln"
        - ".gitlab-ci.yml"

determine-version:
  stage: determine
  image: ubuntu:22.04
  tags:
    - docker
  before_script:
    - apt-get update -qq && apt-get install -y -qq git grep
  script:
    - |
      if [ -f "Pulsar.Server/Properties/AssemblyInfo.cs" ]; then
        VERSION=$(grep -oP '\[assembly: AssemblyVersion\("\K[0-9]+\.[0-9]+\.[0-9]+' Pulsar.Server/Properties/AssemblyInfo.cs || echo "unknown")
        echo "Found version: $VERSION"
        echo "VERSION=$VERSION" >> variables.env
      else
        echo "AssemblyInfo.cs not found"
        echo "VERSION=unknown" >> variables.env
      fi
    - |
      if echo "$CI_COMMIT_MESSAGE" | grep -q "^STABLE"; then
        echo "Stable release detected"
        echo "IS_STABLE=true" >> variables.env
        echo "RELEASE_TYPE=stable" >> variables.env
      else
        echo "Development build"
        echo "IS_STABLE=false" >> variables.env
        echo "RELEASE_TYPE=dev" >> variables.env
      fi
    - echo "Commit short SHA:" $CI_COMMIT_SHORT_SHA
    - echo "Ref name:" $CI_COMMIT_REF_NAME
    - echo "COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" >> variables.env
    - |
      # Clean commit message for dotenv (remove problematic characters)
      CLEAN_MESSAGE=$(echo "$CI_COMMIT_MESSAGE" | tr -d '\n\r' | sed 's/"/\\"/g' | sed "s/'/\\'/g")
      echo "COMMIT_MESSAGE=$CLEAN_MESSAGE" >> variables.env
    - echo "Debug - variables.env contents:"
    - cat variables.env
  artifacts:
    reports:
      dotenv: variables.env
    expire_in: 1 hour

build:
  stage: build
  needs: ["determine-version"]
  image: debian:12
  tags:
    - docker
  before_script:
    # Install Microsoft packages repository and .NET SDK 8.0
    - apt-get update -qq
    - apt-get install -y -qq wget ca-certificates apt-transport-https
    - wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - rm packages-microsoft-prod.deb
    - apt-get update -qq
    - apt-get install -y -qq dotnet-sdk-8.0 zip unzip
  script:
    - echo "Building Pulsar version:" $VERSION
    - echo "Release type:" $RELEASE_TYPE
    - echo "Commit:" $COMMIT_SHORT_SHA
    - echo "Commit message:" $COMMIT_MESSAGE
    - dotnet build $SOLUTION_FILE --configuration $BUILD_CONFIGURATION --output "$CI_PROJECT_DIR/build_output/"
    - |
      if [ "$IS_STABLE" = "true" ]; then
        echo "Creating artifacts for stable build..."
        if [ -f "build_output/Client.exe" ]; then
          mv build_output/Client.exe build_output/Client.bin
          echo "Renamed Client.exe to Client.bin"
        fi
        cd build_output && zip -r ../build_output.zip . && cd ..
        find build_output -type f -name "*.exe" -o -name "*.dll" -o -name "*.bin" | head -20
        ls -la build_output/ || echo "Build output directory listing failed"
      else
        echo "Development build - skipping artifact creation, just verifying compilation"
        ls -la build_output/ || echo "Build output directory listing failed"
      fi
  artifacts:
    paths:
      - build_output.zip
    expire_in: 30 days
    when: always
    rules:
      - if: $IS_STABLE == "true"
