stages:
  - determine
  - build
  - release

variables:
  SOLUTION_FILE: "Pulsar.sln"
  BUILD_CONFIGURATION: "Release"
  TARGET_FRAMEWORK: "net472"

# Only run on main branch when C# files or project files change
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - "**/*.cs"
        - "**/*.csproj"
        - "**/*.sln"
        - ".gitlab-ci.yml"

determine-version:
  stage: determine
  image: ubuntu:22.04
  tags:
    - docker
  before_script:
    - apt-get update -qq && apt-get install -y -qq git grep
  script:
    - |
      if [ -f "Pulsar.Server/Properties/AssemblyInfo.cs" ]; then
        VERSION=$(grep -oP '\[assembly: AssemblyVersion\("\K[0-9]+\.[0-9]+\.[0-9]+' Pulsar.Server/Properties/AssemblyInfo.cs || echo "unknown")
        echo "Found version: $VERSION"
        echo "VERSION=$VERSION" >> variables.env
      else
        echo "AssemblyInfo.cs not found"
        echo "VERSION=unknown" >> variables.env
      fi
    - |
      if echo "$CI_COMMIT_MESSAGE" | grep -q "^STABLE"; then
        echo "Stable release detected"
        echo "IS_STABLE=true" >> variables.env
        echo "RELEASE_TYPE=stable" >> variables.env
      else
        echo "Development build"
        echo "IS_STABLE=false" >> variables.env
        echo "RELEASE_TYPE=dev" >> variables.env
      fi
    - echo "Commit short SHA:" $CI_COMMIT_SHORT_SHA
    - echo "Ref name:" $CI_COMMIT_REF_NAME
    - echo "COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" >> variables.env
    - |
      # Clean commit message for dotenv (remove problematic characters)
      CLEAN_MESSAGE=$(echo "$CI_COMMIT_MESSAGE" | tr -d '\n\r' | sed 's/"/\\"/g' | sed "s/'/\\'/g")
      echo "COMMIT_MESSAGE=$CLEAN_MESSAGE" >> variables.env
    - echo "Debug - variables.env contents:"
    - cat variables.env
  artifacts:
    reports:
      dotenv: variables.env
    expire_in: 1 hour

build:
  stage: build
  needs: ["determine-version"]
  image: debian:12
  tags:
    - docker
  before_script:
    # Install Microsoft packages repository and .NET SDK 8.0
    - apt-get update -qq
    - apt-get install -y -qq wget ca-certificates apt-transport-https
    - wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - rm packages-microsoft-prod.deb
    - apt-get update -qq
    - apt-get install -y -qq dotnet-sdk-8.0 zip unzip
  script:
    - echo "Building Pulsar version:" $VERSION
    - echo "Release type:" $RELEASE_TYPE
    - echo "Commit:" $COMMIT_SHORT_SHA
    - echo "Commit message:" $COMMIT_MESSAGE
    - dotnet build $SOLUTION_FILE --configuration $BUILD_CONFIGURATION --output "$CI_PROJECT_DIR/build_output/"
    - cd build_output && zip -r ../build_output.zip . && cd ..
    - find build_output -type f -name "*.exe" -o -name "*.dll" -o -name "*.bin" | head -20
    - ls -la build_output/ || echo "Build output directory listing failed"
  artifacts:
    paths:
      - build_output.zip
      - build_output/
      - setup.bat
    expire_in: 1 week

upload-package:
  stage: release
  needs: ["determine-version", "build"]
  image: curlimages/curl:latest
  tags:
    - docker
  rules:
    - if: $IS_STABLE == "true"
      variables:
        PACKAGE_NAME: "pulsar-stable"
    - if: $IS_STABLE == "false"
      variables:
        PACKAGE_NAME: "pulsar-dev"
  script:
    - |
      # Force HTTPS for API calls since the server redirects HTTP to HTTPS
      export HTTPS_API_V4_URL="${CI_API_V4_URL/http:/https:}"
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --upload-file build_output.zip \
           "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${VERSION}/build_output.zip"

release-stable:
  stage: release
  needs: ["determine-version", "build"]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^STABLE/'
  before_script:
    # Debug: Print all environment variables
    - echo "[DEBUG] IS_STABLE value is:" "$IS_STABLE"
    - echo "[DEBUG] VERSION value is:" "$VERSION"
    - echo "[DEBUG] RELEASE_TYPE value is:" "$RELEASE_TYPE"
    - env | grep -E "(IS_STABLE|VERSION|RELEASE_TYPE)" || echo "No matching env vars found"
    # Install jq and curl for JSON parsing and uploads
    - apk add --no-cache jq curl
    # Force HTTPS for API calls since the server redirects HTTP to HTTPS
    - export HTTPS_API_V4_URL="${CI_API_V4_URL/http:/https:}"
    - |
      if curl --silent --fail --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
         "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/AutoBuild" > /dev/null 2>&1; then
        echo "Deleting existing stable release..."
        curl --request DELETE --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
             "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/AutoBuild"
      fi
    - |
      if curl --silent --fail --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
         "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags/AutoBuild" > /dev/null 2>&1; then
        echo "Deleting existing stable tag..."
        curl --request DELETE --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
             "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags/AutoBuild"
      fi
  script:
    # Debug: List all files in workspace and build_output
    - echo "[DEBUG] Listing root directory contents:"
    - ls -la
    - echo "[DEBUG] Listing build_output directory contents:"
    - ls -la build_output || echo "No build_output directory"
    - echo "[DEBUG] Checking for files to upload:"
    - |
      for file in build_output.zip build_output/Pulsar.exe build_output/Client.exe setup.bat; do
        if [ -f "$file" ]; then
          echo "[DEBUG] Found $file, uploading..."
          curl --verbose --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               --form "file=@$file" \
               "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/uploads" \
               -o "upload_$(basename $file).json"
        else
          echo "[DEBUG] File $file not found!"
        fi
      done
    - echo "[DEBUG] Uploaded file responses:"
    - cat upload_build_output.zip.json || echo "No upload_build_output.zip.json"
    - cat upload_Pulsar.exe.json || echo "No upload_Pulsar.exe.json"
    - cat upload_Client.exe.json || echo "No upload_Client.exe.json"
    - cat upload_setup.bat.json || echo "No upload_setup.bat.json"
    - |
      BUILD_ZIP_URL=$(jq -r '.url' upload_build_output.zip.json 2>/dev/null || echo "")
      SERVER_EXE_URL=$(jq -r '.url' upload_Pulsar.exe.json 2>/dev/null || echo "")
      CLIENT_EXE_URL=$(jq -r '.url' upload_Client.exe.json 2>/dev/null || echo "")
      SETUP_BAT_URL=$(jq -r '.url' upload_setup.bat.json 2>/dev/null || echo "")
      echo "BUILD_ZIP_URL=$BUILD_ZIP_URL" >> variables.env
      echo "SERVER_EXE_URL=$SERVER_EXE_URL" >> variables.env
      echo "CLIENT_EXE_URL=$CLIENT_EXE_URL" >> variables.env
      echo "SETUP_BAT_URL=$SETUP_BAT_URL" >> variables.env
  release:
    tag_name: "AutoBuild"
    name: "Pulsar Stable"
    description: |
      # Pulsar Stable Build
      **Version:** $VERSION
      **Built from branch:** $CI_COMMIT_BRANCH
      **Build date:** $CI_PIPELINE_CREATED_AT
      **Commit:** $COMMIT_SHORT_SHA
      **Commit message:** $COMMIT_MESSAGE

      This is the stable automated build triggered by a commit message starting with 'STABLE'.
    assets:
      links:
        - name: "build_output.zip"
          url: "${CI_PROJECT_URL}${BUILD_ZIP_URL}"
          link_type: "package"
        - name: "DONT_DOWNLOAD_SERVER.exe"
          url: "${CI_PROJECT_URL}${SERVER_EXE_URL}"
          link_type: "other"
        - name: "DONT_DOWNLOAD_CLIENT.exe"
          url: "${CI_PROJECT_URL}${CLIENT_EXE_URL}"
          link_type: "other"
        - name: "RUN_ME.bat"
          url: "${CI_PROJECT_URL}${SETUP_BAT_URL}"
          link_type: "other"

release-dev:
  stage: release
  needs: ["determine-version", "build"]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - docker
  rules:
    - if: $IS_STABLE == "false"
  before_script:
    # Install jq and curl for JSON parsing and uploads
    - apk add --no-cache jq curl
    # Force HTTPS for API calls since the server redirects HTTP to HTTPS
    - export HTTPS_API_V4_URL="${CI_API_V4_URL/http:/https:}"
    - |
      if curl --silent --fail --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
         "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/AutoBuild-Dev" > /dev/null 2>&1; then
        echo "Deleting existing dev release..."
        curl --request DELETE --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
             "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/AutoBuild-Dev"
      fi
    - |
      if curl --silent --fail --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
         "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags/AutoBuild-Dev" > /dev/null 2>&1; then
        echo "Deleting existing dev tag..."
        curl --request DELETE --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
             "${HTTPS_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags/AutoBuild-Dev"
      fi
  script:
    - echo "Creating development release for version:" "$VERSION"
  release:
    tag_name: "AutoBuild-Dev"
    name: "Pulsar Development"
    description: |
      # Pulsar Development Build
      **Version:** $VERSION (Development)
      **Built from branch:** $CI_COMMIT_BRANCH
      **Build date:** $CI_PIPELINE_CREATED_AT
      **Commit:** $COMMIT_SHORT_SHA
      **Commit message:** $COMMIT_MESSAGE
      
      This is the development build with the latest features and may be unstable.
    assets:
      links:
        - name: "build_output.zip"
          url: "${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_SHA}/raw/build_output.zip?job=build"
          link_type: "package"
