name: Pulsar .NET 9.0 Windows Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore Pulsar.sln

      - name: Build Client
        run: dotnet build Pulsar.Client/Pulsar.Client.csproj --configuration Release --no-restore

      - name: Publish Server
        run: dotnet publish Pulsar.Server/Pulsar.Server.csproj --configuration Release --output "./publish/server" --no-restore

      - name: Prepare Build Output
        run: |
          New-Item -ItemType Directory -Path "./build_output" -Force
          Copy-Item -Path "./publish/server/*" -Destination "./build_output/" -Recurse -Force
          if (Test-Path "./bin/Release/net9.0-windows/client.bin") {
            Copy-Item -Path "./bin/Release/net9.0-windows/client.bin" -Destination "./build_output/client.bin" -Force
          } elseif (Test-Path "./bin/Release/net472/Client.exe") {
            Copy-Item -Path "./bin/Release/net472/Client.exe" -Destination "./build_output/client.bin" -Force
          } else {
            Write-Host "Warning: Client executable not found"
          }
        shell: pwsh

      - name: Zip Build Output
        run: Compress-Archive -Path "./build_output/*" -DestinationPath "pulsar-net-win64.zip"
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: pulsar-net-win64.zip

      - name: Delete existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete Pulsar-v2.2 --yes --cleanup-tag || echo "No existing release/tag to delete"
        shell: bash

      - name: Create Release 
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         gh release create Pulsar-v2.2 pulsar-net-win64.zip \
         -t "Pulsar-v2.2" \
         -n "Automated build release for Pulsar v2.2" \
         --draft=false \
         --prerelease=false
        shell: bash
